### PR TITLE
Extracts attester in the "target" directory by default

### LINKED ISSUE #8: Corrupted attester tmp directory
Hello,

I have currently integrated attester plugin into 1A UI build process to facilitate UI test-driven development.
However, I notice that during some random circumstances the extracted attester directory is corrupted on the server and has caused all pull requests being rejected.

Here's the log:
[ERROR] Failed to execute goal com.ariatemplates.attester:attester-maven-plugin:1.5.0:test (default) on project aodb_ui: Execution default of goal com.ariatemplates.attester:attester-maven-plugin:1.5.0:test failed: Failed to find or extract attester: Could not find file: /tmp/com.ariatemplates.attester-attester-1.5.0-project/attester/bin/attester.js -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.ariatemplates.attester:attester-maven-plugin:1.5.0:test (default) on project aodb_ui: Execution default of goal com.ariatemplates.attester:attester-maven-plugin:1.5.0:test failed: Failed to find or extract attester
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal com.ariatemplates.attester:attester-maven-plugin:1.5.0:test failed: Failed to find or extract attester
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:143)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: java.lang.RuntimeException: Failed to find or extract attester
	at com.ariatemplates.attester.maven.RunAttester.extractDependency(RunAttester.java:277)
	at com.ariatemplates.attester.maven.RunAttester.extractAttester(RunAttester.java:283)
	at com.ariatemplates.attester.maven.RunAttester.execute(RunAttester.java:289)
	at com.ariatemplates.attester.maven.RunTests.execute(RunTests.java:105)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	... 20 more
Caused by: java.io.FileNotFoundException: Could not find file: /tmp/com.ariatemplates.attester-attester-1.5.0-project/attester/bin/attester.js
	at com.ariatemplates.attester.maven.RunAttester.extractDependency(RunAttester.java:274)
	... 24 more

Quick investigation reveals that this issue may be linked to parallel builds on the server. I can simply remove the tmp directory but this won't completely solve the root cause.

I have 2 proposals to overcome the issue:
* extract attester framework all the time by prefixing directory with timestamp or random values and delete it after test completion
or
* enhance the logic to validate attester directory is available and not corrupted else override it

Could you please advise if you can implement any of these proposals?
Thanks & Best regards,
Imam

### PR DESCRIPTION
**Pull request by divdavem**
attester javascript files are now extracted in the local maven "target" directory by default instead of being extracted in the global temporary directory (`java.io.tmpdir`).

(in order to fix #8)

### CODE REVIEW

**Comment by jakub-g** [comment]
LGTM

File: src/main/java/com/ariatemplates/attester/maven/ArtifactExtractor.java [hunk 1]
```diff
@@ -88,12 +96,18 @@ public static String getPropertyName(Dependency dependency) {
     }
 
     public static File getOutputDirectory(Artifact artifact) {
```
Comment (ihabibi) [inline src/main/java/com/ariatemplates/attester/maven/ArtifactExtractor.java]: Just small remark for the code change, I notice this static method is no more used and thus you can remove it.

Comment (divdavem) [inline src/main/java/com/ariatemplates/attester/maven/ArtifactExtractor.java]: Thank you for your remark. Indeed, this method is not used anymore in attester-maven-plugin.
However, it can be considered as part of the public API of the class, so I think we should remove it in a future (non-backward compatible) release.
